"""
Django settings for prensa project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/



# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*bnfuleu3q8tf7bd58=)2v78(%a7w_f7q3u1^c$79og@_o25a@'

# SECURITY WARNING: don't run with debug turned on in production!
# 1. Detección de entorno (Pon esto donde tenías el if anterior)
if 'runserver' in sys.argv:
    # --- CONFIGURACIÓN LOCAL ---
    DEBUG = True
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
    CSRF_COOKIE_DOMAIN = None
    SESSION_COOKIE_DOMAIN = None
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
else:
    # --- CONFIGURACIÓN PRODUCCIÓN (Nginx) ---
    DEBUG = True  # Cámbialo a False cuando ya no necesites ver errores
    ALLOWED_HOSTS = ['prensa.atizapan.gob.mx', 'atizapan.gob.mx']
    CSRF_COOKIE_DOMAIN = ".atizapan.gob.mx"
    SESSION_COOKIE_DOMAIN = ".atizapan.gob.mx"
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# 2. Orígenes de confianza (Esto se puede quedar fijo, no estorba en local)
CSRF_TRUSTED_ORIGINS = [
    'https://prensa.atizapan.gob.mx',
    'https://*.atizapan.gob.mx'
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sala',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'prensa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # AGREGA ESTA LÍNEA PARA QUE BUSQUE EN TU CARPETA DE LA RAÍZ
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'prensa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


STATIC_URL = 'static/'
# Esto le dice a Django dónde buscar los archivos estáticos globales
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# --- CONFIGURACIÓN PARA ENVIAR CORREOS ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
# El correo desde donde saldrán los mensajes (Tu "cartero")
EMAIL_HOST_USER = 'sub.medios@atizapan.gob.mx' 
# La contraseña de aplicación de ese correo
EMAIL_HOST_PASSWORD = 'lspj tkwz ymxa gnzc'

