version: '3.8'

services:
  web:
    build: .
    container_name: sala_prensa_app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Sincroniza tu código en tiempo real
    environment:
      - DEBUG=1