# Generated by Django 6.0.3 on 2026-03-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Evento')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.CharField(default='Por confirmar', max_length=50, verbose_name='Hora')),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('cobertura', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cobertura (Reporteros)')),
            ],
            options={
                'verbose_name': 'Evento de Agenda',
                'verbose_name_plural': 'Eventos de Agenda',
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
