# Generated by Django 6.0.3 on 2026-03-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='agenda_fotos/', verbose_name='Foto del Evento'),
        ),
    ]
