# Generated by Django 6.0.3 on 2026-03-19 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0002_evento_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-fecha', 'hora'], 'verbose_name': 'Evento de Agenda', 'verbose_name_plural': 'Eventos de Agenda'},
        ),
        migrations.RemoveField(
            model_name='evento',
            name='imagen',
        ),
        migrations.AddField(
            model_name='evento',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='agenda_documentos/', verbose_name='Documento Word (.docx)'),
        ),
        migrations.AddField(
            model_name='evento',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='agenda_fotos/portadas/', verbose_name='Foto de Portada'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='cobertura',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cobertura'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='hora',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Título del Evento'),
        ),
        migrations.CreateModel(
            name='ImagenEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='agenda_fotos/galeria/')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='sala.evento')),
            ],
        ),
    ]
