# Generated by Django 6.0.3 on 2026-03-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0003_alter_evento_options_remove_evento_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='contenido',
            field=models.TextField(blank=True, null=True, verbose_name='Cuerpo Completo de la Noticia'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Corta'),
        ),
    ]
