# Generated by Django 6.0.3 on 2026-03-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0004_evento_contenido_alter_evento_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='agenda_audios/', verbose_name='Audio / Entrevista'),
        ),
        migrations.AddField(
            model_name='evento',
            name='nota_extra',
            field=models.FileField(blank=True, null=True, upload_to='agenda_notas/', verbose_name='Nota / PDF Adicional'),
        ),
        migrations.AddField(
            model_name='evento',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='agenda_videos/', verbose_name='Video del Evento'),
        ),
    ]
